package com.redhat.coolstore;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label("PromoEvent")
@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
@org.kie.api.definition.type.Timestamp("timestamp")
public class PromoEvent implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ItemId")
   @org.kie.api.definition.type.Position(0)
   private java.lang.String itemId;

   @org.kie.api.definition.type.Label("percentOff")
   @org.kie.api.definition.type.Position(1)
   private double percentOff;

   @org.kie.api.definition.type.Label("Timestamp")
   private java.util.Date timestamp;

   public PromoEvent()
   {
   }

   public java.lang.String getItemId()
   {
      return this.itemId;
   }

   public void setItemId(java.lang.String itemId)
   {
      this.itemId = itemId;
   }

   public double getPercentOff()
   {
      return this.percentOff;
   }

   public void setPercentOff(double percentOff)
   {
      this.percentOff = percentOff;
   }

   public java.util.Date getTimestamp()
   {
      return this.timestamp;
   }

   public void setTimestamp(java.util.Date timestamp)
   {
      this.timestamp = timestamp;
   }

   public PromoEvent(java.lang.String itemId, double percentOff,
         java.util.Date timestamp)
   {
      this.itemId = itemId;
      this.percentOff = percentOff;
      this.timestamp = timestamp;
   }

   public PromoEvent(java.lang.String itemId, double percentOff)
   {
      this.itemId = itemId;
      this.percentOff = percentOff;
   }
}