package com.redhat.coolstore;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label("PromoEvent")
@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
public class PromoEvent implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ItemId")
   @org.kie.api.definition.type.Position(0)
   private java.lang.String itemId;

   @org.kie.api.definition.type.Label("percentOff")
   @org.kie.api.definition.type.Position(1)
   private double percentOff;

   @org.kie.api.definition.type.Label("PromoID")
   private java.lang.String promoId;

   public PromoEvent()
   {
   }

   public java.lang.String getItemId()
   {
      return this.itemId;
   }

   public void setItemId(java.lang.String itemId)
   {
      this.itemId = itemId;
   }

   public double getPercentOff()
   {
      return this.percentOff;
   }

   public void setPercentOff(double percentOff)
   {
      this.percentOff = percentOff;
   }

   public java.lang.String getPromoId()
   {
      return this.promoId;
   }

   public void setPromoId(java.lang.String promoId)
   {
      this.promoId = promoId;
   }

   public PromoEvent(java.lang.String itemId, double percentOff,
         java.lang.String promoId)
   {
      this.itemId = itemId;
      this.percentOff = percentOff;
      this.promoId = promoId;
   }

   public PromoEvent(java.lang.String itemId, double percentOff)
   {
      this.itemId = itemId;
      this.percentOff = percentOff;
   }
}